### ISSUE TITLE
Cannot run demo

### ISSUE THREAD

**Issue by fegan104** [plusmobileapps/ktor-firebase-auth-sample#4]
Hello, 

I'm pretty new to ktor and found this repository and [blog post](https://plusmobileapps.com/2022/08/02/ktor-firebase-auth.html) very helpful, but I can't get the authenticated routes work. I checked out the repo, added my service account json, built and ran the project without issue. However, when I GET `http://0.0.0.0:8080/authenticated` in Postman (using Bearer Token auth) this line `FirebaseAuth.getInstance().verifyIdToken(authHeader.blob)` throws an error with this stack trace.

```
com.google.firebase.auth.FirebaseAuthException: Unknown error while making a remote service call: Connection refused (Connection refused)
        at com.google.firebase.auth.internal.AuthErrorHandler.createException(AuthErrorHandler.java:122)
        at com.google.firebase.auth.internal.AuthErrorHandler.createException(AuthErrorHandler.java:35)
        at com.google.firebase.internal.AbstractHttpErrorHandler.handleIOException(AbstractHttpErrorHandler.java:63)
        at com.google.firebase.internal.ErrorHandlingHttpClient.send(ErrorHandlingHttpClient.java:110)
        at com.google.firebase.auth.internal.AuthHttpClient.sendRequest(AuthHttpClient.java:75)
        at com.google.firebase.auth.FirebaseUserManager.lookupUserAccount(FirebaseUserManager.java:238)
        at com.google.firebase.auth.FirebaseUserManager.getUserById(FirebaseUserManager.java:121)
        at com.google.firebase.auth.RevocationCheckDecorator.validateDisabledOrRevoked(RevocationCheckDecorator.java:59)
        at com.google.firebase.auth.RevocationCheckDecorator.verifyToken(RevocationCheckDecorator.java:54)
        at com.google.firebase.auth.AbstractFirebaseAuth$3.execute(AbstractFirebaseAuth.java:307)
        at com.google.firebase.auth.AbstractFirebaseAuth$3.execute(AbstractFirebaseAuth.java:304)
        at com.google.firebase.internal.CallableOperation.call(CallableOperation.java:36)
        at com.google.firebase.auth.AbstractFirebaseAuth.verifyIdToken(AbstractFirebaseAuth.java:269)
        at com.google.firebase.auth.AbstractFirebaseAuth.verifyIdToken(AbstractFirebaseAuth.java:241)
        at com.plusmobileapps.firebaseadminsample.firebase.FirebaseAuthKt$verifyFirebaseIdToken$token$1.invokeSuspend(FirebaseAuth.kt:80)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:508)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:276)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:375)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:396)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
        at com.google.firebase.internal.ErrorHandlingHttpClient.send(ErrorHandlingHttpClient.java:96)
        ... 19 more
```

**Comment by fegan104** [comment]
In case it's useful for the Authentication header I'm getting my idToken from `https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key={{FIREBASE_API_KEY}}` and passing in my test account credentials. And using the returned `idToken` just as the blog post describes.

Though it seems like it might be a Firebase Admin sdk issue. But I didn't change the version in the `build.gradle` and I'm using my personal device, and don't have any firewalls or proxies set up that would prevent Admin SDK from being able to make http calls

**Comment by plusmobileapps** [comment]
It might help to see the whole project you have and the curl request you made to better help you out? 

Not sure if you have seen [this](https://firebase.google.com/docs/reference/admin/error-handling#platform-error-codes) page, but seems like based off that error your app might only be connected to your local network? Hard to know though without seeing what code you have written.

**Comment by fegan104** [comment]
Thank you for the quick response! To your first question:
> It might help to see the whole project you have and the curl request you made to better help you out?

The error I'm seeing is in this project. I git cloned this project, and followed the setup section of your README, and then  `./gradlew run` the project exactly as you describe. I made no other modifications to the code. The same for the curl requests. I initially tried with Postman but I did re-try with the curl request from your blog post.

> your app might only be connected to your local network

Is there something that you did to configure you project so that this wasn't the case? I haven't seen anything in the docs for the admin sdk that describe this behavior or what to do about it. Are there environment vars that need to be set or something that might not have been mentioned in the set up section of your README? I certainly can't think of any reason my network would prevent Firebase making network calls.

**Comment by fegan104** [comment]
I finally figured out what the issue was. I had previously enabled Firebase Auth Emulator by setting `FIREBASE_AUTH_EMULATOR_HOST` and although I had tried unsetting it with the unset command in zsh I needed to delete this line from my ~/.zshrc. Then after restarting IntelliJ it finally worked.

```
export FIREBASE_AUTH_EMULATOR_HOST="localhost:9099"
```
